name: upper-image

on:
    push:
        paths:
            - ".github/workflows/upper-image.yml"
            - "upper/**"
    workflow_dispatch: # manual

permissions:
    packages: write
    contents: read

jobs:
    image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: docker version
            - run: docker image build -t upper .
              working-directory: ./upper
              name: test it
            - run: docker container run upper hello welcome to upper
            - uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }} # Rajvir67067
                  password: ${{ secrets.GITHUB_TOKEN }}
            - run: docker tag upper ghrc.io/rajvir67067/upper:latest
            - run: docker tag upper ghrc.io/rajvir67067/upper:${{ github.ref_name }}
            - run: docker push ghrc.io/rajvir67067/upper:latest
            - run: docker push ghrc.io/rajvir67067/upper:${{ github.ref_name }}